--CREATE DATABASE BI_Prac_1_DW;

DROP TABLE IF EXISTS SalesFacts;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Time;
DROP TABLE IF EXISTS Vendor;

CREATE TABLE Customer (
	Customer_Key INT NOT NULL PRIMARY KEY,
	Customer_Name NVARCHAR(255) NOT NULL,
	Address NVARCHAR(255) NULL,
	Phone_Number NVARCHAR(255) NULL,
);

CREATE TABLE Product (
	Product_Key INT NOT NULL PRIMARY KEY,
	Description NVARCHAR(255) NOT NULL,
	Category NVARCHAR(100) NOT NULL,
	Brand NVARCHAR(100) NOT NULL,
);

CREATE TABLE Region (
	Region_Key INT NOT NULL PRIMARY KEY,
	Region_Code NVARCHAR(30) NOT NULL,
	Description NVARCHAR(255) NOT NULL,
);

CREATE TABLE Time (
	Time_Key INT NOT NULL PRIMARY KEY,
	Year INT NOT NULL,
	Quarter INT NOT NULL,
	Month INT NOT NULL,
	Date DATETIME NOT NULL,
	Day INT NOT NULL,
	DayOfWeek NVARCHAR(100) NOT NULL,
);

CREATE TABLE Vendor (
	Vendor_Key INT NOT NULL PRIMARY KEY,
	Vendor_Name NVARCHAR(255) NOT NULL,
	Address NVARCHAR(255) NULL,
	Phone_Number NVARCHAR(100) NULL,
);

CREATE TABLE SalesFacts (
	Time_Key INT NOT NULL FOREIGN KEY REFERENCES Time(Time_Key) ON DELETE CASCADE ON UPDATE CASCADE,
	Product_Key INT NOT NULL FOREIGN KEY REFERENCES Product(Product_Key) ON DELETE CASCADE ON UPDATE CASCADE,
	Vendor_Key INT NOT NULL FOREIGN KEY REFERENCES Vendor(Vendor_Key) ON DELETE CASCADE ON UPDATE CASCADE,
	Customer_Key INT NOT NULL FOREIGN KEY REFERENCES Customer(Customer_Key) ON DELETE CASCADE ON UPDATE CASCADE,
	Region_Key INT NOT NULL FOREIGN KEY REFERENCES Region(Region_Key) ON DELETE CASCADE ON UPDATE CASCADE,
	Quantity INT NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY(Time_Key, Product_Key, Vendor_Key, Customer_Key, Region_Key),
);